-- Auto-generated from admin/lib/data.ts mock data. Do not hand-edit product rows;
-- regenerate via scratchpad/gen_seed.mjs if the source mock data changes.

insert into public.categories (slug, name, description, image, icon, color) values
  ('smoothies', 'Smoothies', 'Creamy, nutritious blends made from fresh fruits.', '', 'cafe', '#00BFA5'),
  ('juices', 'Juices', 'Cold-pressed fresh juices packed with vitamins.', '', 'flask', '#FF8F00'),
  ('microgreens', 'Microgreens', 'Fresh, nutrient-packed microgreens grown locally.', '', 'leaf', '#2E7D32');

insert into public.products (slug, name, description, price, category_id, unit, weight, nutrition, benefits, storage, is_featured, is_seasonal, is_best_seller, rating, review_count, tags, stock, is_available, created_at) values
  ('strawberry-banana-glow', 'Strawberry Banana Glow', 'A creamy blend of ripe strawberries and sweet bananas.', 99, (select id from public.categories where slug = 'smoothies'), '350ml', '350ml', jsonb_build_object('calories', 210, 'protein', '4g', 'carbs', '44g', 'fat', '2.5g', 'fiber', '4g', 'vitamins', ARRAY['Vitamin C', 'Potassium']::text[]), ARRAY['Rich in antioxidants', 'Boosts skin glow']::text[], 'Refrigerate at 2-4°C.', true, false, true, 4.7, 156, ARRAY['popular', 'creamy']::text[], 100, true, '2024-01-15'::date),
  ('mango-fresh', 'Mango Fresh', 'Pure sunshine in a bottle. Made with handpicked Alphonso mangoes.', 110, (select id from public.categories where slug = 'smoothies'), '350ml', '350ml', jsonb_build_object('calories', 230, 'protein', '3g', 'carbs', '50g', 'fat', '1.5g', 'fiber', '3g', 'vitamins', ARRAY['Vitamin A', 'Vitamin C']::text[]), ARRAY['Excellent source of Vitamin A', 'Boosts immunity']::text[], 'Refrigerate at 2-4°C.', true, false, true, 4.8, 203, ARRAY['tropical', 'mango']::text[], 100, true, '2024-01-20'::date),
  ('choco-chill', 'Choco Chill', 'A decadent blend of premium cocoa, banana, and almond milk.', 115, (select id from public.categories where slug = 'smoothies'), '350ml', '350ml', jsonb_build_object('calories', 250, 'protein', '8g', 'carbs', '38g', 'fat', '7g', 'fiber', '5g', 'vitamins', ARRAY['Iron', 'Magnesium']::text[]), ARRAY['Rich in antioxidants', 'Natural mood booster']::text[], 'Refrigerate at 2-4°C.', true, false, true, 4.9, 189, ARRAY['chocolate', 'protein-rich']::text[], 100, true, '2024-02-01'::date),
  ('papaya-glow', 'Papaya Glow', 'Fresh papaya blended with a hint of lime.', 95, (select id from public.categories where slug = 'smoothies'), '350ml', '350ml', jsonb_build_object('calories', 160, 'protein', '2g', 'carbs', '36g', 'fat', '1g', 'fiber', '5g', 'vitamins', ARRAY['Vitamin C', 'Vitamin A']::text[]), ARRAY['Supports digestion', 'Promotes glowing skin']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.5, 98, ARRAY['light', 'digestion']::text[], 100, true, '2024-02-15'::date),
  ('mint-melon-smoothie', 'Mint Melon Smoothie', 'Sweet melon blended with fresh mint leaves.', 105, (select id from public.categories where slug = 'smoothies'), '350ml', '350ml', jsonb_build_object('calories', 145, 'protein', '3g', 'carbs', '32g', 'fat', '0.5g', 'fiber', '2g', 'vitamins', ARRAY['Vitamin C', 'Potassium']::text[]), ARRAY['Ultra-hydrating', 'Natural cooling effect']::text[], 'Refrigerate at 2-4°C.', true, true, false, 4.6, 87, ARRAY['refreshing', 'seasonal']::text[], 100, true, '2024-03-01'::date),
  ('carrot-lemon-radish-microgreens-juice', 'Carrot, Lemon & Radish Juice', 'Fresh carrot juice blended with zesty lemon and radish microgreens.', 85, (select id from public.categories where slug = 'juices'), '300ml', '300ml', jsonb_build_object('calories', 100, 'protein', '2.5g', 'carbs', '22g', 'fat', '0.5g', 'fiber', '3g', 'vitamins', ARRAY['Vitamin A', 'Vitamin C']::text[]), ARRAY['Excellent for eye health', 'Natural detox support']::text[], 'Refrigerate at all times.', true, false, false, 4.8, 134, ARRAY['cold-pressed', 'immune-boost']::text[], 100, true, '2024-01-25'::date),
  ('cucumber-splash', 'Cucumber Splash', 'Cool cucumber, lemon, and ginger cold-pressed juice.', 90, (select id from public.categories where slug = 'juices'), '300ml', '300ml', jsonb_build_object('calories', 75, 'protein', '2g', 'carbs', '16g', 'fat', '0.3g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin K', 'Potassium']::text[]), ARRAY['Deep hydration', 'Supports skin health']::text[], 'Refrigerate at all times.', false, false, false, 4.4, 76, ARRAY['hydrating', 'detox']::text[], 100, true, '2024-02-10'::date),
  ('apple-sprout', 'Apple Sprout', 'Fresh apples with the nutritional punch of microgreen sprouts.', 99, (select id from public.categories where slug = 'juices'), '300ml', '300ml', jsonb_build_object('calories', 110, 'protein', '1.5g', 'carbs', '26g', 'fat', '0.3g', 'fiber', '2g', 'vitamins', ARRAY['Vitamin C', 'Iron']::text[]), ARRAY['Natural sweetness', 'Supports heart health']::text[], 'Refrigerate at all times.', true, false, false, 4.6, 112, ARRAY['sweet', 'cold-pressed']::text[], 100, true, '2024-03-05'::date),
  ('sweet-lime-spark', 'Sweet Lime Spark', 'Sweet limes cold-pressed at peak ripeness with a hint of mint.', 90, (select id from public.categories where slug = 'juices'), '300ml', '300ml', jsonb_build_object('calories', 85, 'protein', '1g', 'carbs', '20g', 'fat', '0.2g', 'fiber', '0.5g', 'vitamins', ARRAY['Vitamin C', 'Folate']::text[]), ARRAY['Excellent source of Vitamin C', 'Aids digestion']::text[], 'Refrigerate at all times.', false, false, false, 4.5, 94, ARRAY['citrus', 'immunity']::text[], 100, true, '2024-02-20'::date),
  ('watermelon-fresh', 'Watermelon Fresh', 'Fresh juicy watermelon cold-pressed with mint and lime.', 95, (select id from public.categories where slug = 'juices'), '300ml', '300ml', jsonb_build_object('calories', 90, 'protein', '2g', 'carbs', '20g', 'fat', '0.2g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin C', 'Lycopene']::text[]), ARRAY['Deeply hydrating', 'Rich in lycopene']::text[], 'Refrigerate at all times.', false, true, true, 4.7, 145, ARRAY['hydrating', 'summer']::text[], 100, true, '2024-03-10'::date),
  ('pink-radish', 'Pink Radish', 'Crisp and peppery microgreens packed with antioxidants.', 120, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 15, 'protein', '1.5g', 'carbs', '2g', 'fat', '0.5g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin C', 'Vitamin K']::text[]), ARRAY['Rich in antioxidants', 'Supports digestion']::text[], 'Refrigerate at 2-4°C.', false, false, true, 4.6, 54, ARRAY['microgreens', 'peppery']::text[], 100, true, '2024-04-01'::date),
  ('white-radish', 'White Radish', 'Mild yet nutrient-dense, rich in vitamins and minerals.', 120, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 12, 'protein', '1g', 'carbs', '2.5g', 'fat', '0.3g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin C', 'Calcium']::text[]), ARRAY['Supports detoxification', 'Promotes gut health']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.3, 28, ARRAY['microgreens', 'mild']::text[], 100, true, '2024-04-05'::date),
  ('wheatgrass', 'Wheatgrass', 'A powerhouse of chlorophyll and enzymes.', 70, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 20, 'protein', '2g', 'carbs', '4g', 'fat', '0.5g', 'fiber', '2g', 'vitamins', ARRAY['Vitamin A', 'Iron']::text[]), ARRAY['Powerful detox support', 'Boosts natural energy']::text[], 'Refrigerate at 2-4°C.', false, true, false, 4.8, 72, ARRAY['microgreens', 'detox']::text[], 100, true, '2024-04-10'::date),
  ('beetroot', 'Beetroot', 'Earthy and vibrant, loaded with iron and folate.', 199, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 22, 'protein', '2g', 'carbs', '4g', 'fat', '0.3g', 'fiber', '1.5g', 'vitamins', ARRAY['Vitamin A', 'Iron', 'Folate']::text[]), ARRAY['Improves blood circulation', 'Rich in iron']::text[], 'Refrigerate at 2-4°C.', true, false, false, 4.7, 63, ARRAY['microgreens', 'iron-rich']::text[], 100, true, '2024-04-15'::date),
  ('pak-choi', 'Pak Choi', 'Tender and mildly sweet, full of vitamins A, C, and K.', 180, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 13, 'protein', '1.5g', 'carbs', '2g', 'fat', '0.3g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin A', 'Vitamin K', 'Calcium']::text[]), ARRAY['Supports bone health', 'Boosts immunity']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.4, 32, ARRAY['microgreens', 'mild']::text[], 100, true, '2024-04-20'::date),
  ('sunflower', 'Sunflower', 'Nutty and crunchy, packed with protein and healthy fats.', 170, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 25, 'protein', '3g', 'carbs', '3g', 'fat', '1.5g', 'fiber', '1.5g', 'vitamins', ARRAY['Vitamin E', 'Zinc', 'Selenium']::text[]), ARRAY['Promotes muscle recovery', 'High in protein']::text[], 'Refrigerate at 2-4°C.', false, true, false, 4.6, 48, ARRAY['microgreens', 'protein-rich']::text[], 100, true, '2024-05-01'::date),
  ('mustard', 'Mustard', 'Spicy and bold, rich in glucosinolates.', 110, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 15, 'protein', '1.5g', 'carbs', '2g', 'fat', '0.5g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin A', 'Vitamin K']::text[]), ARRAY['Aids metabolism', 'Strengthens immunity']::text[], 'Refrigerate at 2-4°C.', false, false, true, 4.5, 41, ARRAY['microgreens', 'spicy']::text[], 100, true, '2024-05-05'::date),
  ('fenugreek', 'Fenugreek', 'Mildly bitter with a hint of maple, supports digestion.', 110, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 18, 'protein', '2g', 'carbs', '3g', 'fat', '0.5g', 'fiber', '2g', 'vitamins', ARRAY['Vitamin A', 'Iron']::text[]), ARRAY['Supports blood sugar balance', 'Aids digestion']::text[], 'Refrigerate at 2-4°C.', false, false, true, 4.5, 37, ARRAY['microgreens', 'digestion']::text[], 100, true, '2024-05-10'::date),
  ('broccoli', 'Broccoli', 'Mild and nutrient-dense, packed with sulforaphane.', 220, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 17, 'protein', '2g', 'carbs', '2.5g', 'fat', '0.4g', 'fiber', '1.5g', 'vitamins', ARRAY['Vitamin A', 'Vitamin K', 'Sulforaphane']::text[]), ARRAY['Packed with sulforaphane', 'Supports detoxification']::text[], 'Refrigerate at 2-4°C.', true, false, false, 4.9, 81, ARRAY['microgreens', 'superfood']::text[], 100, true, '2024-05-15'::date),
  ('arugula', 'Arugula', 'Peppery and aromatic, high in antioxidants.', 220, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 14, 'protein', '1.5g', 'carbs', '2g', 'fat', '0.4g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin A', 'Vitamin K']::text[]), ARRAY['Boosts heart health', 'High in antioxidants']::text[], 'Refrigerate at 2-4°C.', true, false, false, 4.7, 59, ARRAY['microgreens', 'peppery']::text[], 100, true, '2024-05-20'::date),
  ('turnip', 'Turnip', 'Mild and slightly sweet, rich in fiber and vitamin C.', 99, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 12, 'protein', '1g', 'carbs', '2.5g', 'fat', '0.3g', 'fiber', '1g', 'vitamins', ARRAY['Vitamin C', 'Calcium']::text[]), ARRAY['Supports gut health', 'Rich in vitamin C']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.2, 22, ARRAY['microgreens', 'mild']::text[], 100, true, '2024-05-25'::date),
  ('red-amaranth', 'Red Amaranth', 'Vibrant and earthy, packed with iron and amino acids.', 199, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 20, 'protein', '2.5g', 'carbs', '3g', 'fat', '0.5g', 'fiber', '1.5g', 'vitamins', ARRAY['Vitamin A', 'Iron', 'Calcium']::text[]), ARRAY['Promotes blood health', 'Supports muscle recovery']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.5, 35, ARRAY['microgreens', 'iron-rich']::text[], 100, true, '2024-06-01'::date),
  ('red-cabbage', 'Red Cabbage', 'Mild and slightly sweet, loaded with anthocyanins.', 220, (select id from public.categories where slug = 'microgreens'), '50gm', '50gm', jsonb_build_object('calories', 16, 'protein', '1.5g', 'carbs', '3g', 'fat', '0.3g', 'fiber', '1.5g', 'vitamins', ARRAY['Vitamin C', 'Vitamin K', 'Anthocyanins']::text[]), ARRAY['Supports brain function', 'Reduces inflammation']::text[], 'Refrigerate at 2-4°C.', false, false, false, 4.4, 26, ARRAY['microgreens', 'anti-inflammatory']::text[], 100, true, '2024-06-10'::date);

insert into public.subscription_plans (name, description, price, unit, delivery_frequency, items, benefits, is_popular, color) values
  ('Starter', 'Perfect for individuals starting their wellness journey', 399, 'week', 'Weekly', ARRAY['2 smoothies', '1 fresh juice', 'Free delivery']::text[], ARRAY['Free delivery', 'Flexible skip', 'Cancel anytime']::text[], false, '#4CAF50'),
  ('Wellness', 'Our most popular plan for daily freshness', 699, 'week', 'Weekly', ARRAY['4 smoothies', '3 fresh juices', '1 seasonal special']::text[], ARRAY['Free delivery', 'Priority support', 'Cancel anytime']::text[], true, '#2E7D32'),
  ('Family', 'Complete freshness for the whole family', 1199, 'week', 'Weekly', ARRAY['6 smoothies', '6 fresh juices', '2 seasonal specials']::text[], ARRAY['Free delivery', 'Priority support', '15% off add-ons', 'Cancel anytime']::text[], false, '#1B5E20'),
  ('Active Greens Box', 'Curated microgreens box for the health-conscious', 499, 'week', 'Weekly', ARRAY['3 microgreens', '1 seasonal special', 'Care instructions']::text[], ARRAY['Free delivery', 'Flexible skip', 'Cancel anytime']::text[], false, '#66BB6A'),
  ('Golden Years Box', 'Nourishing microgreens crafted for senior wellness', 599, 'week', 'Weekly', ARRAY['2 nutrient-dense microgreens', '1 wellness shot pack', 'Senior-friendly recipes']::text[], ARRAY['Free delivery', 'Flexible skip', 'Cancel anytime']::text[], false, '#FFA726'),
  ('Workplace Wellness Box', 'Keep your team thriving with fresh microgreens weekly', 699, 'week', 'Weekly', ARRAY['5 assorted microgreens', '2 wellness shots', 'Team recipes']::text[], ARRAY['Free delivery', 'Priority support', 'Bulk ordering', 'Cancel anytime']::text[], true, '#42A5F5');

