import type { JournalBlock, JournalPost } from "./journal";

const p = (text: string): JournalBlock => ({ type: "p", text });
const h = (text: string): JournalBlock => ({ type: "h2", text });
const l = (...items: string[]): JournalBlock => ({ type: "list", items });

const img = (slug: string) => `/images/journal/${slug}.webp`;

// Search-driven posts (see BLOG_SEO_PLAN.md). Health copy is deliberately general:
// no cure/treatment claims, and readers with medical conditions are pointed to a doctor.
export const SEO_JOURNAL_POSTS: JournalPost[] = [
  {
    slug: "how-to-grow-microgreens-at-home-in-india",
    title: "How To Grow Microgreens At Home In India",
    date: "28 September 2026",
    readTime: "6 min read",
    category: "Kitchen",
    excerpt:
      "A beginner's step-by-step guide to growing microgreens at home in India: what you need, which seeds to pick, and how to harvest in 7 to 10 days.",
    image: img("how-to-grow-microgreens-at-home-in-india"),
    imageAlt: "A tray of broccoli and radish microgreens on a wooden table with a spray bottle and seed packet",
    body: [
      p("Microgreens are one of the easiest things you can grow indoors. You need no garden, very little space and about ten minutes a day. Most varieties are ready to cut in 7 to 10 days, which makes them a good first project for anyone in an Indian apartment."),
      h("What you need to start"),
      l(
        "A shallow tray with drainage holes (a reused food container with holes works).",
        "A growing medium: cocopeat is the easiest to find in India and stays clean and light. Tissue paper or jute mats also work.",
        "Untreated seeds sold for sprouting or microgreens. Avoid seeds coated with fungicide.",
        "A spray bottle for gentle watering.",
        "A bright spot with indirect light, such as a window sill. A small grow light helps in dim flats.",
      ),
      h("Which microgreens are easiest for beginners"),
      p("Start with radish, mustard, sunflower or green gram (moong). They germinate fast, forgive small mistakes and grow in warm Indian weather without special care. Broccoli and beetroot are slower, so try them once you have the rhythm."),
      h("Step-by-step method"),
      l(
        "Soak larger seeds such as sunflower and pea for 6 to 8 hours. Small seeds like radish and mustard don't need soaking.",
        "Fill the tray with about an inch of damp cocopeat and level it.",
        "Spread the seeds evenly and press them lightly into the surface. Don't bury them.",
        "Mist well, then cover the tray with another tray or a plate for 2 to 3 days to keep it dark and humid.",
        "Uncover once the seeds have sprouted and move the tray to bright, indirect light.",
        "Mist once or twice a day, or bottom-water, so the surface stays damp but never soggy.",
        "Harvest with clean scissors just above the soil when the first true leaves open, usually day 7 to 10.",
      ),
      h("Can you grow microgreens without soil?"),
      p("Yes. Tissue paper, cotton or jute mats work well because microgreens only need moisture, air and light for the first week or so. Rinse the mat daily to avoid mould, and expect slightly thinner stems than you would get in cocopeat."),
      h("Common mistakes"),
      l(
        "Overwatering, which leads to mould and rot. If you see white fuzz on the surface, it is usually mould rather than root hair: reduce water and add airflow.",
        "Sowing too thickly. Crowded seeds trap moisture.",
        "Too little light, which gives long, pale, weak stems.",
        "Eating the roots. Always cut above the soil line and wash the greens.",
      ),
      h("Prefer to skip the growing?"),
      p("If you would rather have them ready to eat, Mini Greens harvests microgreens to order and delivers them fresh across Bangalore. Growing at home is still a great way to see how much goes into every tray."),
    ],
  },
  {
    slug: "best-microgreens-and-their-benefits",
    title: "Best Microgreens And Their Benefits",
    date: "27 September 2026",
    readTime: "5 min read",
    category: "Nutrition",
    excerpt:
      "Broccoli, radish, sunflower, pea, beetroot and mustard: what each popular microgreen tastes like and what it offers nutritionally.",
    image: img("best-microgreens-and-their-benefits"),
    imageAlt: "Small bowls of assorted microgreens including broccoli, radish, sunflower and pea shoots",
    body: [
      p("Microgreens are the young seedlings of vegetables and herbs, harvested when the first leaves appear. They are small, but studies of their nutrient content suggest they can hold higher concentrations of vitamins and plant compounds than the mature vegetables, gram for gram. Here is a practical guide to the varieties people ask about most."),
      h("Broccoli microgreens"),
      p("Mild and slightly peppery, broccoli microgreens are known for sulforaphane-related compounds, along with vitamin C and K. They work well in salads, sandwiches and smoothies."),
      h("Radish microgreens"),
      p("Bright, spicy and quick to grow. Radish microgreens add a sharp bite to eggs, tacos and rice bowls, and provide vitamin C and folate."),
      h("Sunflower shoots"),
      p("Crunchy and nutty, with thicker stems. Sunflower shoots contain some plant protein and healthy fats and hold up well when tossed in salads."),
      h("Pea shoots"),
      p("Sweet, tender and tasting like fresh peas. Pea shoots are a good source of vitamin C and fibre and are lovely lightly stir-fried or added to noodles."),
      h("Beetroot microgreens"),
      p("Earthy, with red stems that make any plate look better. They provide folate and add a mild beet flavour without the sweetness of the root."),
      h("Mustard microgreens"),
      p("Hot, wasabi-like and full of flavour. A few leaves go a long way in wraps and dressings."),
      h("How to choose and eat them"),
      l(
        "Look for crisp stems, bright colour and no slime or musty smell.",
        "Add them at the end of cooking, or raw, to keep texture and flavour.",
        "Rotate varieties: each offers a slightly different mix of nutrients and taste.",
      ),
      p("Microgreens are a nutritious addition to a varied diet, not a cure for anything. If you have a medical condition or are pregnant, talk to your doctor about dietary changes."),
    ],
  },
  {
    slug: "buy-microgreens-in-bangalore",
    title: "Buy Microgreens In Bangalore: Price And Delivery Guide",
    date: "26 September 2026",
    readTime: "4 min read",
    category: "Farm",
    excerpt:
      "Where to buy fresh microgreens in Bangalore, what they should cost, and how to tell a fresh tray from a tired one.",
    image: img("buy-microgreens-in-bangalore"),
    imageAlt: "A hand holding a box of freshly harvested mixed microgreens in a bright Bangalore kitchen",
    body: [
      p("Demand for microgreens in Bangalore has grown quickly, with more farms, cafés and home cooks looking for a reliable fresh supply. Here is how to buy well, and what to look out for."),
      h("Where to buy microgreens in Bangalore"),
      l(
        "Directly from a local farm or brand that harvests to order and delivers to your door.",
        "Organic stores and farmers' markets, which may stock trays or boxes weekly.",
        "Quick-commerce apps, which are convenient but may hold stock for several days.",
      ),
      h("What do microgreens cost in India?"),
      p("Prices vary by variety and quantity. Broccoli, beetroot and sunflower usually cost more than radish or mustard because they take longer or need more seed. Expect to pay noticeably more per kilo than for mature vegetables, because you are buying a delicate, hand-harvested product with a short shelf life. Check the current price on each product page in our shop."),
      h("How to spot fresh microgreens"),
      l(
        "Crisp, upright stems and bright green leaves.",
        "No wet, slimy patches or sour smell.",
        "A recent harvest date on the pack. Fresh microgreens keep for about 5 to 7 days in a fridge.",
        "Sold on the tray or cut to order rather than pre-washed and sitting in cold storage.",
      ),
      h("Why harvest-to-order matters"),
      p("Microgreens continue to age once they are cut. A tray harvested the morning it ships tastes sweeter, lasts longer and loses fewer nutrients than one that has spent days in transit. That is why Mini Greens cuts to order and delivers across Bangalore."),
      h("Ready to order?"),
      p("Browse fresh trays, tea blends and juices in the shop, or set up a weekly subscription so your greens arrive without you having to think about it."),
    ],
  },
  {
    slug: "broccoli-microgreens-benefits-nutrition-recipes",
    title: "Broccoli Microgreens: Benefits, Nutrition And Recipes",
    date: "25 September 2026",
    readTime: "5 min read",
    category: "Nutrition",
    excerpt:
      "What broccoli microgreens are, how they compare to mature broccoli, and simple ways to eat them every day.",
    image: img("broccoli-microgreens-benefits-nutrition-recipes"),
    imageAlt: "A dense tray of dark green broccoli microgreens with a bowl of harvested shoots",
    body: [
      p("Broccoli microgreens are broccoli seedlings cut about a week to ten days after sowing. They taste mild and fresh, with a hint of the cabbage family's peppery edge, and they are among the most popular microgreens in India."),
      h("Nutrition in brief"),
      p("Broccoli microgreens are a source of vitamin C, vitamin K, folate and plant compounds called glucosinolates, which are the precursors of sulforaphane. Laboratory analyses of young brassica shoots have found notable concentrations of these compounds compared with mature heads, but portion sizes matter: you eat a small handful, so treat them as a nutritious boost rather than a main source."),
      h("Broccoli microgreens vs broccoli"),
      l(
        "Mature broccoli gives you more fibre and bulk per serving.",
        "Microgreens deliver concentrated plant compounds in a small, raw portion.",
        "Eating both is the best plan.",
      ),
      h("Easy ways to eat broccoli microgreens"),
      l(
        "Toss a handful into salads or grain bowls.",
        "Layer them into sandwiches, wraps and burgers.",
        "Blend a small handful into a green smoothie with banana and apple.",
        "Scatter over dal, soup or eggs just before serving.",
      ),
      h("Storage and safety tips"),
      p("Keep them dry in a container lined with paper towel and use within a week. Rinse gently before eating. Broccoli microgreens are generally safe for healthy adults; people on blood thinners should ask their doctor about vitamin K intake."),
      p("Mini Greens grows broccoli microgreens pesticide-free and cuts them to order, so what arrives at your door is as fresh as a tray can be."),
    ],
  },
  {
    slug: "microgreens-vs-sprouts",
    title: "Microgreens vs Sprouts: What's The Difference?",
    date: "24 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "They sound alike but are grown, eaten and handled differently. Here is how microgreens and sprouts compare on taste, nutrition and safety.",
    image: img("microgreens-vs-sprouts"),
    imageAlt: "A jar of pale sprouts next to a tray of leafy green microgreens for comparison",
    body: [
      p("Microgreens and sprouts are often mixed up, but they are different foods. The main differences come down to how they grow and what part you eat."),
      h("How they are grown"),
      p("Sprouts are germinated in water in a jar or tray, usually for 2 to 5 days, with no soil and no light. You eat the whole thing: seed, root and shoot. Microgreens are sown on soil or a growing mat, exposed to light and grown for 7 to 21 days. You cut the stem and leaves above the roots."),
      h("Taste and texture"),
      l(
        "Sprouts are crunchy, watery and mild.",
        "Microgreens have a fuller flavour, with colourful leaves and often a peppery or sweet finish.",
      ),
      h("Nutrition"),
      p("Both are nutritious. Microgreens have true leaves that photosynthesise, so they build more of the pigments and vitamins associated with leafy greens. Sprouts tend to be higher in some enzymes and starch-related changes from germination. Neither replaces a varied diet."),
      h("Food safety"),
      p("Sprouts are grown in warm, humid, sealed conditions, which is ideal for bacteria. That is why food safety agencies advise pregnant women, children and older adults to cook them. Microgreens are grown in open air and cut above the roots, so the risk is lower, though washing and fresh storage still matter."),
      h("Which should you choose?"),
      p("Choose sprouts if you like a crunchy, budget-friendly topping and will cook or rinse them well. Choose microgreens for flavour, colour and versatility in raw dishes. Many people happily eat both."),
    ],
  },
  {
    slug: "do-microgreens-have-protein",
    title: "Do Microgreens Have Protein?",
    date: "23 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "Microgreens contain some protein, and sunflower and pea shoots contain more than most. Here is what to realistically expect.",
    image: img("do-microgreens-have-protein"),
    imageAlt: "A bowl of sunflower and pea shoot microgreens beside chickpeas, lentils and pumpkin seeds",
    body: [
      p("Yes, microgreens contain protein, but they are not a major protein source on their own. Because you eat them in small handfuls, they add a little protein and a lot of freshness rather than replacing dal, paneer, eggs or chicken."),
      h("Which microgreens have the most protein?"),
      l(
        "Sunflower shoots: among the higher-protein varieties, with a nutty, crunchy texture.",
        "Pea shoots: legume-based, so naturally richer in protein than leafy varieties.",
        "Lentil, chickpea and moong shoots: also legume-based and good for salads and stir-fries.",
        "Broccoli, radish and beetroot: lower in protein, valued more for vitamins and plant compounds.",
      ),
      h("How much protein are you really getting?"),
      p("A typical serving is around 20 to 30 grams. Even the higher-protein varieties will contribute only a small amount at that size. To get more, eat generous portions of legume shoots, or combine microgreens with protein-rich foods."),
      h("Easy high-protein ways to use them"),
      l(
        "Add pea shoots to a chickpea salad.",
        "Top sprouted moong chaat with sunflower shoots.",
        "Stuff a paneer or egg wrap with a handful of mixed microgreens.",
        "Blend pea shoots into a hummus for extra colour.",
      ),
      p("Think of microgreens as a nutritious add-on to your protein, not a substitute. If you are planning a high-protein diet, a dietitian can help you tailor it."),
    ],
  },
  {
    slug: "microgreens-for-weight-loss",
    title: "Are Microgreens Good For Weight Loss?",
    date: "22 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "Microgreens are low in calories and high in flavour, which can help you eat better. Here is how to use them sensibly.",
    image: img("microgreens-for-weight-loss"),
    imageAlt: "A healthy grain bowl topped with fresh microgreens beside a glass of water",
    body: [
      p("No single food causes weight loss, and microgreens are no exception. But they can support a balanced eating pattern because they are very low in calories, add volume and flavour and make healthy meals more appealing."),
      h("Why they can help"),
      l(
        "Low in calories: a generous handful adds very few.",
        "Flavour without extras: peppery radish or mustard can reduce the urge to add heavy sauces.",
        "They encourage more vegetables: a colourful bowl is easier to stick with.",
        "Contain some fibre and water, which add to a feeling of fullness.",
      ),
      h("How to eat them for a healthier plate"),
      l(
        "Use them to top dal, khichdi, roti wraps and salads.",
        "Add a handful to your breakfast eggs or oats instead of extra cheese.",
        "Blend them with fruit into a smoothie, and keep an eye on added sugar.",
        "Swap a fried snack for a microgreens and sprouts chaat.",
      ),
      h("What to keep in mind"),
      p("Weight change depends on your overall diet, sleep, activity and health. Microgreens work best alongside protein, whole grains and regular movement. Be wary of any product promising fast results, including detox teas and juices."),
      p("If you are managing a health condition or taking medication, speak to your doctor or a registered dietitian before making significant diet changes."),
    ],
  },
  {
    slug: "best-microgreens-recipes-salads-smoothies",
    title: "Best Microgreens Recipes: Salads, Smoothies And More",
    date: "21 September 2026",
    readTime: "5 min read",
    category: "Kitchen",
    excerpt:
      "Six easy ways to cook and serve microgreens at home, from a five-minute green smoothie to a proper salad bowl.",
    image: img("best-microgreens-recipes-salads-smoothies"),
    imageAlt: "A green smoothie, avocado toast and salad bowl all topped with fresh microgreens",
    body: [
      p("Microgreens are small, but they change a plate. These are the six ways we eat them most often at home, all simple enough for a weekday."),
      h("1. Green smoothie"),
      p("Blend a handful of pea shoots or mild broccoli microgreens with a ripe banana, half an apple, a squeeze of lime and water or coconut water. The fruit hides any grassy notes."),
      h("2. Avocado toast"),
      p("Mash avocado on toasted bread, add salt, pepper and lemon, and finish with a tuft of radish or sunflower microgreens for crunch and colour."),
      h("3. Everyday salad bowl"),
      p("Layer cucumber, tomato, boiled chickpeas and roasted peanuts, then top with mixed microgreens. Dress with olive oil, lemon and a pinch of chaat masala."),
      h("4. Egg wrap or omelette"),
      p("Add microgreens after cooking so they stay crisp. Mustard and radish work best with eggs."),
      h("5. Soup and dal garnish"),
      p("Stir a small handful into a hot bowl of dal or soup just before serving. The heat softens the leaves slightly and releases their aroma."),
      h("6. Quick chutney or dressing"),
      p("Blend coriander, mint and pea shoots with green chilli, lemon and yoghurt for a bright green dip."),
      h("Tips for best results"),
      l(
        "Add microgreens at the end. Long cooking wilts them.",
        "Rinse gently and pat dry so dressings cling.",
        "Match strength to dish: mild pea and broccoli for smoothies, spicy radish and mustard for wraps.",
      ),
    ],
  },
  {
    slug: "microgreens-for-diabetes",
    title: "Microgreens And Diabetes: What To Know",
    date: "20 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "Can microgreens fit into a diabetes-friendly diet? A cautious, plain-language look at what they can and cannot do.",
    image: img("microgreens-for-diabetes"),
    imageAlt: "A balanced Indian plate of millet roti, dal and vegetables garnished with microgreens",
    body: [
      p("Microgreens do not treat or cure diabetes, and nothing you read online should replace your doctor's plan. What they can do is add flavour, colour and micronutrients to meals without adding many carbohydrates."),
      h("Why they fit a balanced plate"),
      l(
        "Very low in carbohydrates and calories per serving.",
        "Provide vitamins, minerals and plant compounds, and a little fibre.",
        "Make vegetable-heavy meals more enjoyable, which helps consistency.",
      ),
      h("What the research says"),
      p("Some early laboratory and animal studies on brassica and fenugreek shoots have looked at blood sugar and antioxidant markers, but human evidence is limited. Treat these results as interesting, not as advice."),
      h("Ways to add them to a diabetes-friendly diet"),
      l(
        "Top millet, dal or vegetable meals with a handful of microgreens.",
        "Pair them with protein and fibre rather than refined carbohydrates.",
        "Watch smoothies: use vegetables and microgreens first and keep fruit portions modest.",
      ),
      h("Talk to your care team"),
      p("If you manage diabetes or take medication, ask your doctor or a registered dietitian how new foods fit your plan. Fenugreek and other herbs can interact with some medicines, so it is worth checking before making them a daily habit."),
    ],
  },
  {
    slug: "microgreen-tea-benefits-when-to-drink",
    title: "Microgreen Tea Benefits And When To Drink It",
    date: "19 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "What green and herbal tea blends offer, when to drink them, and how to brew a better cup.",
    image: img("microgreen-tea-benefits-when-to-drink"),
    imageAlt: "A glass cup of pale green herbal tea with mint and lemon beside a bowl of dried tea blend",
    body: [
      p("Tea is one of the simplest ways to add plants to your day. Green and herbal blends contain plant compounds such as polyphenols, and many people find a warm cup helps them slow down."),
      h("What tea blends can offer"),
      l(
        "Hydration with flavour and no sugar.",
        "Antioxidant plant compounds, especially in green tea.",
        "A gentle caffeine lift in green tea, or none at all in herbal blends.",
        "A calming ritual that can replace snack-time sugar.",
      ),
      h("When to drink it"),
      l(
        "Morning: a green tea blend as a lighter alternative to a second coffee.",
        "Between meals: it may be gentler on the stomach than on an empty one.",
        "After dinner: choose a caffeine-free herbal blend such as mint or lemon.",
        "Avoid caffeinated tea close to bedtime if it affects your sleep.",
      ),
      h("How to brew a better cup"),
      l(
        "Use water just off the boil, around 80 degrees for green tea.",
        "Steep for 2 to 3 minutes. Longer makes it bitter.",
        "Use fresh, dry leaves stored in an airtight container.",
        "Add lemon or a little honey if you like, but keep it light.",
      ),
      h("A word on detox claims"),
      p("Your liver and kidneys do the detoxing. Tea can be part of a healthy routine, but it will not flush toxins or melt fat. If you are pregnant, breastfeeding or on medication, check with your doctor about herbs and caffeine."),
      p("Explore Mini Greens' tea blends in the shop to try fresh, small-batch flavours."),
    ],
  },
  {
    slug: "microgreens-side-effects-and-safety",
    title: "Microgreens Side Effects And Safety Tips",
    date: "18 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "Microgreens are safe for most people. Here is how to wash, store and eat them safely, and who should take extra care.",
    image: img("microgreens-side-effects-and-safety"),
    imageAlt: "Hands rinsing fresh microgreens in a colander under running water",
    body: [
      p("Microgreens are generally safe for healthy adults, and side effects are uncommon. Like any fresh, raw produce, they need sensible handling."),
      h("Possible side effects"),
      l(
        "Mild stomach upset if you eat a lot after not eating many greens.",
        "Allergic reactions in people sensitive to a specific plant such as mustard or pea.",
        "Interference with medicines: greens high in vitamin K can affect blood thinners.",
      ),
      h("Food safety basics"),
      l(
        "Buy from a grower who uses clean water and clean trays.",
        "Cut above the roots and never eat the root mat or soil.",
        "Rinse gently under cool running water and pat dry.",
        "Keep them refrigerated and eat within 5 to 7 days.",
        "Throw away anything slimy, smelly or discoloured.",
      ),
      h("Who should take extra care"),
      p("Pregnant women, young children, older adults and anyone with a weakened immune system should be careful with raw produce in general. Wash microgreens well, or lightly cook them, and ask your doctor if you are unsure."),
      h("Are microgreens grown safely?"),
      p("At Mini Greens, trays are grown indoors without pesticides, harvested to order and packed the same morning. If you are ever unsure about a batch, contact us."),
    ],
  },
  {
    slug: "how-to-store-microgreens",
    title: "How To Store Microgreens So They Stay Fresh",
    date: "17 September 2026",
    readTime: "3 min read",
    category: "Kitchen",
    excerpt:
      "Microgreens are delicate. These storage tips keep them crisp for up to a week.",
    image: img("how-to-store-microgreens"),
    imageAlt: "Fresh microgreens stored in a glass container lined with paper towel in a refrigerator",
    body: [
      p("Microgreens are alive and delicate, so how you store them decides whether they stay crisp for days or turn to mush overnight."),
      h("The simple method"),
      l(
        "Keep them cool: store in the fridge at 3 to 5 degrees as soon as they arrive.",
        "Keep them dry: excess water is the main cause of slime. Blot with paper towel if damp.",
        "Line a container with paper towel, add the microgreens loosely, and close with a loosely fitted lid so they can breathe.",
        "Store them on the middle shelf, not against the back wall where things freeze.",
      ),
      h("Growing tray? Do this instead"),
      p("If you receive a live tray, keep it in a cool, bright place and mist lightly. Cut only what you need each day and the rest will stay fresh longer."),
      h("How long do they last?"),
      p("Cut microgreens generally last 5 to 7 days when stored well. Live trays can last a little longer if kept cool and watered gently."),
      h("Signs they have gone off"),
      l(
        "Slimy or wet leaves.",
        "A sour or musty smell.",
        "Dark, translucent stems.",
      ),
      p("When in doubt, throw them out. For more on making your weekly box last, see our guide on keeping your greens alive for a week."),
    ],
  },
  {
    slug: "how-to-start-a-microgreens-business-in-india",
    title: "How To Start A Microgreens Business In India",
    date: "16 September 2026",
    readTime: "6 min read",
    category: "Farm",
    excerpt:
      "What it really takes to grow and sell microgreens in India: setup, costs to plan for, customers and the mistakes to avoid.",
    image: img("how-to-start-a-microgreens-business-in-india"),
    imageAlt: "An indoor microgreens farm with white shelving racks, grow lights and rows of trays",
    body: [
      p("Microgreens are a low-space, fast-cycle crop, which is why so many people in Indian cities are exploring them as a small business. It can work, but it is a farming and delivery business first, and margins depend on selling steadily."),
      h("What you need to get started"),
      l(
        "A clean, ventilated indoor space, even a spare room or terrace corner.",
        "Racks, trays, cocopeat or grow mats, and good-quality seed.",
        "Reliable light. Natural light with grow lights as backup keeps output consistent.",
        "Clean water and a simple washing and packing area.",
        "Food-safe packaging and, when you sell, the required FSSAI registration.",
      ),
      h("Who buys microgreens?"),
      l(
        "Cafés, restaurants and hotels looking for garnish and salad ingredients.",
        "Health-conscious households on weekly subscriptions.",
        "Organic and specialty stores.",
        "Quick-commerce and e-commerce platforms.",
      ),
      h("What to plan for"),
      p("Your costs are seed, growing medium, packaging, labour, electricity and delivery. Your income depends on how many trays you can grow, harvest and actually sell before they age. Start small, measure waste and pricing carefully, and grow varieties that customers reorder."),
      h("Common mistakes"),
      l(
        "Growing before you have buyers.",
        "Ignoring hygiene and food safety.",
        "Overpromising health claims.",
        "Underpricing and forgetting delivery cost.",
      ),
      h("Partner with Mini Greens"),
      p("If you would rather focus on growing, or you own a café or store and want a dependable supply, our partner programme is built for you. Apply on our partner page and we will get in touch."),
    ],
  },
  {
    slug: "sunflower-and-pea-shoots-benefits",
    title: "Sunflower And Pea Shoots: Benefits And How To Eat Them",
    date: "15 September 2026",
    readTime: "4 min read",
    category: "Nutrition",
    excerpt:
      "Two of the most popular, hearty microgreens. What sunflower and pea shoots offer and how to cook with them.",
    image: img("sunflower-and-pea-shoots-benefits"),
    imageAlt: "Piles of fresh sunflower shoots and pea shoots on a light wooden board with seeds",
    body: [
      p("Sunflower and pea shoots are the sturdy, sweet members of the microgreens family. They have thicker stems, a satisfying crunch and a flavour most people enjoy straight away."),
      h("Sunflower shoots"),
      p("Nutty and juicy, sunflower shoots offer some plant protein, healthy fats, vitamin E and B vitamins. Their crunch makes them a good salad base or sandwich filling."),
      h("Pea shoots"),
      p("Sweet, fresh and grassy, pea shoots provide vitamin C, vitamin A and fibre. They are the easiest microgreen to cook with because they hold up well to heat."),
      h("How to eat them"),
      l(
        "Toss sunflower shoots into a salad with lemon and olive oil.",
        "Wilt pea shoots in a pan with garlic for 30 seconds as a side dish.",
        "Blend pea shoots into a chutney or hummus.",
        "Stack either in a sandwich or wrap for crunch.",
      ),
      h("Buying and storing tips"),
      p("Look for firm stems and bright colour. Store dry and cool, and eat within 5 to 7 days. Both varieties are available fresh from Mini Greens, cut to order in Bangalore."),
    ],
  },
  {
    slug: "microgreens-for-kids",
    title: "Microgreens For Kids: Fun Ways To Grow And Eat Them",
    date: "14 September 2026",
    readTime: "4 min read",
    category: "Kitchen",
    excerpt:
      "Growing and eating microgreens can turn fussy eaters into curious ones. Here are simple, child-friendly ideas.",
    image: img("microgreens-for-kids"),
    imageAlt: "A smiling child sprinkling microgreens on a bowl of pasta at a kitchen table",
    body: [
      p("Children are far more likely to try a vegetable they have grown or helped prepare. Microgreens are perfect for that: quick, visible and small enough for little hands."),
      h("Grow them together"),
      p("Radish and moong grow fast, often sprouting in two to three days, so children see results before they lose interest. Let them sow the seeds, mist the tray and measure the growth with a ruler."),
      h("Kid-friendly ways to eat microgreens"),
      l(
        "Sprinkle mild pea shoots over pasta or noodles.",
        "Add them to cheese sandwiches or rolls.",
        "Blend a small handful into a fruit smoothie.",
        "Let children snip and add their own topping at the table.",
      ),
      h("Tips for fussy eaters"),
      l(
        "Start with mild varieties like pea or sunflower shoots before spicy radish or mustard.",
        "Offer a small amount and let them touch and smell first.",
        "Keep it playful and avoid pressure to finish.",
      ),
      h("Safety notes"),
      p("Wash microgreens well before serving to young children, and supervise scissors and trays. If your child has food allergies, introduce new plants one at a time and check with your paediatrician."),
    ],
  },
];
